[package]
name = "world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { version = "0.14.1", features = ["webgl2"]}
wasm-bindgen = "0.2.93"
web-sys = "0.3.70"
